// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clients": {
            "get": {
                "description": "Returns all configured clients (devices, Telegram bots, etc.)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "List clients",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.ClientDefinition"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new client. A unique auth token is generated automatically.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Create client",
                "parameters": [
                    {
                        "description": "Client definition (token is auto-generated)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.ClientDefinition"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/store.ClientDefinition"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/admin.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/types": {
            "get": {
                "description": "Returns registered client types with config field specifications for dynamic form rendering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "List client types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/admin.ClientTypeInfo"
                            }
                        }
                    }
                }
            }
        },
        "/clients/{id}": {
            "get": {
                "description": "Returns a client by its unique ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Get client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.ClientDefinition"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates a client by ID. Token and ID are preserved.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Update client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Client definition",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.ClientDefinition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.ClientDefinition"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/admin.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a client by ID, revoking its access token",
                "tags": [
                    "clients"
                ],
                "summary": "Delete client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clients/{id}/regenerate-token": {
            "post": {
                "description": "Generates a new authentication token for a client, invalidating the previous one",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Regenerate client token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.ClientDefinition"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/admin.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.ClientTypeInfo": {
            "type": "object",
            "properties": {
                "configSchema": {
                    "$ref": "#/definitions/client.Schema"
                },
                "displayName": {
                    "type": "string",
                    "example": "Telegram"
                },
                "type": {
                    "type": "string",
                    "example": "telegram"
                }
            }
        },
        "admin.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "resource not found"
                }
            }
        },
        "client.Schema": {
            "type": "object",
            "additionalProperties": true
        },
        "store.ClientConfig": {
            "type": "object",
            "properties": {
                "cron": {
                    "$ref": "#/definitions/store.CronClientConfig"
                },
                "discord": {
                    "$ref": "#/definitions/store.DiscordClientConfig"
                },
                "slack": {
                    "$ref": "#/definitions/store.SlackClientConfig"
                },
                "telegram": {
                    "$ref": "#/definitions/store.TelegramClientConfig"
                },
                "webhook": {
                    "$ref": "#/definitions/store.WebhookClientConfig"
                }
            }
        },
        "store.ClientDefinition": {
            "type": "object",
            "properties": {
                "allowedAgents": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "config": {
                    "$ref": "#/definitions/store.ClientConfig"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "store.CronClientConfig": {
            "type": "object",
            "properties": {
                "commandId": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                }
            }
        },
        "store.DiscordClientConfig": {
            "type": "object",
            "properties": {
                "allowedChannels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "allowedUsers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "botToken": {
                    "type": "string"
                },
                "guildId": {
                    "type": "string"
                }
            }
        },
        "store.SlackClientConfig": {
            "type": "object",
            "properties": {
                "allowedChannels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "allowedUsers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "botToken": {
                    "type": "string"
                },
                "signingSecret": {
                    "type": "string"
                }
            }
        },
        "store.TelegramClientConfig": {
            "type": "object",
            "properties": {
                "allowedChats": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "allowedUsers": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "botToken": {
                    "type": "string"
                },
                "responseMode": {
                    "type": "string"
                }
            }
        },
        "store.WebhookClientConfig": {
            "type": "object",
            "properties": {
                "commandId": {
                    "type": "string"
                },
                "passthrough": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1/admin",
	Schemes:          []string{"http"},
	Title:            "Magec Admin API",
	Description:      "Administration API for managing Magec multi-agent voice assistant resources.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
