package artifacts

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"

	"google.golang.org/adk/agent"
	"google.golang.org/adk/model"
	"google.golang.org/adk/tool"
	"google.golang.org/adk/tool/functiontool"
	"google.golang.org/genai"
)

// Toolset provides ADK tools for managing artifacts (files generated by the LLM
// or attached by the user).
//
// save_artifact, list_artifacts and export_artifact are plain function tools.
// load_artifact is special: instead of returning the artifact content as JSON
// (which would force the model to deal with base64 noise and burn context), it
// implements the RequestProcessor pattern. The Run() result only carries the
// requested filename; ProcessRequest() then appends the actual genai.Part
// (text or inlineData) to the LLMRequest.Contents so the provider delivers it
// to the model in its native multimodal format. This mirrors the design of
// ADK's own loadartifactstool.
//
// The toolset receives a tempDirProvider closure at construction time so it
// stays decoupled from the Store: the closure's caller is responsible for
// resolving the path (typically via Store.ResolveTemporaryDir, the single
// source of truth for that location). The provider is invoked on every call,
// so changes to Settings.TemporaryDir take effect on the next invocation
// without recreating the toolset.
//
// urlBuilder follows the same decoupling principle for ephemeral artifact
// URLs: the toolset builds an ArtifactURLRequest from session context and
// hands it off; the closure (wired in main.go) decides the signing secret,
// the public hostname and the expiration window. The toolset never reads
// configuration directly. When urlBuilder returns an error, get_artifact_url
// surfaces it to the LLM as a structured failure.
type Toolset struct {
	tools           []tool.Tool
	tempDirProvider func() string
	urlBuilder      ArtifactURLBuilder
}

// ArtifactURLRequest is the descriptor handed to ArtifactURLBuilder. Tools
// gather it from tool.Context and the artifact metadata, the builder turns
// it into a fully-qualified URL.
type ArtifactURLRequest struct {
	AppName   string
	UserID    string
	SessionID string
	Name      string
	MIMEType  string
}

// ArtifactURLResult is what the builder returns. URL is the fully-qualified
// link, ExpiresAt is the absolute Unix timestamp at which it stops working.
type ArtifactURLResult struct {
	URL       string
	ExpiresAt int64
}

// ArtifactURLBuilder is the closure injected into the toolset to produce
// ephemeral artifact URLs. Returning an error means the builder cannot
// produce a URL right now (e.g. signing secret not configured); the tool
// surfaces that to the LLM with a clear message.
type ArtifactURLBuilder func(req ArtifactURLRequest) (ArtifactURLResult, error)

// NewToolset initializes the save/load/list/export/url artifact tools.
//
// tempDirProvider returns the absolute directory where export_artifact writes
// transient files. Callers must guarantee a non-empty path; export_artifact
// does not perform any fallback of its own.
//
// urlBuilder is optional: when nil, get_artifact_url is not registered. This
// lets deployments that intentionally disable signed URLs (for example,
// because they have not configured a signing secret) skip the tool entirely
// instead of advertising a capability that always fails.
func NewToolset(tempDirProvider func() string, urlBuilder ArtifactURLBuilder) (*Toolset, error) {
	if tempDirProvider == nil {
		return nil, fmt.Errorf("tempDirProvider is required")
	}
	ts := &Toolset{tempDirProvider: tempDirProvider, urlBuilder: urlBuilder}

	saveTool, err := functiontool.New(
		functiontool.Config{
			Name: "save_artifact",
			Description: "Save a file artifact (code, documents, data, images, etc.) that will be delivered to the user as a downloadable file. " +
				"Use this instead of pasting long code blocks or file contents directly in chat. " +
				"For text content, provide it directly in the 'content' field. " +
				"For binary content (images, PDFs, etc.), set 'is_base64' to true and provide base64-encoded data in 'content'. " +
				"The artifact persists across the current session.",
		},
		ts.saveArtifact,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create save_artifact tool: %w", err)
	}

	listTool, err := functiontool.New(
		functiontool.Config{
			Name:        "list_artifacts",
			Description: "List all artifacts saved in the current session. Returns the filenames of all available artifacts.",
		},
		ts.listArtifacts,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create list_artifacts tool: %w", err)
	}

	exportTool, err := functiontool.New(
		functiontool.Config{
			Name: "export_artifact",
			Description: "Export an artifact's content to a file in the system temporary directory and return its absolute path on disk. " +
				"Use this when you need to hand an artifact off to another tool that reads from the filesystem (e.g. to run a parser, converter or text extractor). " +
				"The destination file is created with a unique name derived from the artifact name; the directory is chosen for you and cannot be overridden. " +
				"Returns the absolute path, byte size and MIME type so the caller can pass them to the next tool.",
		},
		ts.exportArtifact,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create export_artifact tool: %w", err)
	}

	ts.tools = []tool.Tool{saveTool, &loadArtifactTool{}, listTool, exportTool}

	if urlBuilder != nil {
		urlTool, err := functiontool.New(
			functiontool.Config{
				Name: "get_artifact_url",
				Description: "Issue a short-lived, signed download URL for an artifact. " +
					"Use this when you need to hand an artifact off to another tool that fetches files over HTTP (e.g. when the consumer runs in a different process or container and cannot reach the local filesystem). " +
					"The URL serves the artifact's raw bytes with the correct MIME type, requires no authentication header, and stops working after a server-defined expiration. " +
					"Returns the URL, the absolute expiration timestamp, and the MIME type.",
			},
			ts.getArtifactURL,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create get_artifact_url tool: %w", err)
		}
		ts.tools = append(ts.tools, urlTool)
	}
	return ts, nil
}

func (ts *Toolset) Name() string {
	return "artifact_toolset"
}

func (ts *Toolset) Tools(_ agent.ReadonlyContext) ([]tool.Tool, error) {
	return ts.tools, nil
}

// SaveArgs defines the parameters expected by the save_artifact tool.
type SaveArgs struct {
	Name     string `json:"name"`
	Content  string `json:"content"`
	MIMEType string `json:"mime_type,omitempty"`
	IsBase64 bool   `json:"is_base64,omitempty"`
}

// SaveResult defines the response returned by the save_artifact tool.
type SaveResult struct {
	Success bool   `json:"success"`
	Version int64  `json:"version"`
	Message string `json:"message"`
}

func (ts *Toolset) saveArtifact(ctx tool.Context, args SaveArgs) (SaveResult, error) {
	if args.Name == "" {
		return SaveResult{Success: false, Message: "name is required"}, nil
	}
	if args.Content == "" {
		return SaveResult{Success: false, Message: "content is required"}, nil
	}

	var part *genai.Part
	if args.IsBase64 {
		data, err := base64.StdEncoding.DecodeString(args.Content)
		if err != nil {
			return SaveResult{Success: false, Message: fmt.Sprintf("invalid base64 content: %v", err)}, nil
		}
		mimeType := args.MIMEType
		if mimeType == "" {
			mimeType = "application/octet-stream"
		}
		part = &genai.Part{
			InlineData: &genai.Blob{
				MIMEType: mimeType,
				Data:     data,
			},
		}
	} else {
		part = genai.NewPartFromText(args.Content)
	}

	resp, err := ctx.Artifacts().Save(ctx, args.Name, part)
	if err != nil {
		return SaveResult{Success: false, Message: fmt.Sprintf("failed to save: %v", err)}, nil
	}

	return SaveResult{
		Success: true,
		Version: resp.Version,
		Message: fmt.Sprintf("Artifact '%s' saved (version %d). It will be delivered to the user as a file.", args.Name, resp.Version),
	}, nil
}

type ListArgs struct{}

type ListResult struct {
	Success   bool     `json:"success"`
	Artifacts []string `json:"artifacts"`
	Count     int      `json:"count"`
	Message   string   `json:"message"`
}

func (ts *Toolset) listArtifacts(ctx tool.Context, _ ListArgs) (ListResult, error) {
	resp, err := ctx.Artifacts().List(ctx)
	if err != nil {
		return ListResult{Success: false, Message: fmt.Sprintf("failed to list artifacts: %v", err)}, nil
	}

	return ListResult{
		Success:   true,
		Artifacts: resp.FileNames,
		Count:     len(resp.FileNames),
		Message:   fmt.Sprintf("Found %d artifact(s)", len(resp.FileNames)),
	}, nil
}

// ExportArgs are the inputs to export_artifact.
type ExportArgs struct {
	Name string `json:"name"`
}

// ExportResult is what the model receives after a successful export.
type ExportResult struct {
	Success  bool   `json:"success"`
	Path     string `json:"path,omitempty"`
	Size     int    `json:"size,omitempty"`
	MIMEType string `json:"mime_type,omitempty"`
	Message  string `json:"message"`
}

// exportArtifact loads an artifact through the session artifact service,
// decodes it to raw bytes (text → UTF-8, inlineData → original binary), and
// writes those bytes to a fresh file under the directory returned by the
// configured tempDirProvider. The destination filename is derived from the
// artifact name plus a random suffix injected by os.CreateTemp, so concurrent
// exports of the same artifact never collide.
//
// All user-facing errors are returned as ExportResult{Success:false} so the
// LLM gets a structured message rather than a tool failure event. Real Go
// errors are reserved for impossible states (nil provider).
func (ts *Toolset) exportArtifact(ctx tool.Context, args ExportArgs) (ExportResult, error) {
	if args.Name == "" {
		return ExportResult{Success: false, Message: "name is required"}, nil
	}

	dir := ts.tempDirProvider()
	if dir == "" {
		return ExportResult{Success: false, Message: "no temporary directory configured"}, nil
	}

	resp, err := ctx.Artifacts().Load(ctx, args.Name)
	if err != nil {
		return ExportResult{Success: false, Message: fmt.Sprintf("artifact %q not found: %v", args.Name, err)}, nil
	}
	if resp == nil || resp.Part == nil {
		return ExportResult{Success: false, Message: fmt.Sprintf("artifact %q has no content", args.Name)}, nil
	}

	var (
		payload  []byte
		mimeType string
	)
	switch {
	case resp.Part.InlineData != nil:
		payload = resp.Part.InlineData.Data
		mimeType = resp.Part.InlineData.MIMEType
		if mimeType == "" {
			mimeType = "application/octet-stream"
		}
	case resp.Part.Text != "":
		payload = []byte(resp.Part.Text)
		mimeType = "text/plain"
	default:
		return ExportResult{Success: false, Message: fmt.Sprintf("artifact %q is empty", args.Name)}, nil
	}

	// os.CreateTemp inserts a random suffix between the literal "*" and the
	// rest of the pattern. Keeping the artifact's original basename + extension
	// lets downstream tools (extractors, viewers) identify the format from the
	// path alone.
	base := filepath.Base(args.Name)
	ext := filepath.Ext(base)
	stem := base[:len(base)-len(ext)]
	if stem == "" {
		stem = "artifact"
	}
	pattern := stem + "-*" + ext

	f, err := os.CreateTemp(dir, pattern)
	if err != nil {
		return ExportResult{Success: false, Message: fmt.Sprintf("failed to create file in %q: %v", dir, err)}, nil
	}
	path := f.Name()
	if _, err := f.Write(payload); err != nil {
		f.Close()
		os.Remove(path)
		return ExportResult{Success: false, Message: fmt.Sprintf("failed to write %q: %v", path, err)}, nil
	}
	if err := f.Close(); err != nil {
		os.Remove(path)
		return ExportResult{Success: false, Message: fmt.Sprintf("failed to close %q: %v", path, err)}, nil
	}

	return ExportResult{
		Success:  true,
		Path:     path,
		Size:     len(payload),
		MIMEType: mimeType,
		Message:  fmt.Sprintf("Artifact %q exported to %s (%d bytes, %s).", args.Name, path, len(payload), mimeType),
	}, nil
}

// loadArtifactTool implements load_artifact using ADK's RequestProcessor
// pattern: Run() returns only metadata (the requested filename), and
// ProcessRequest() splices the real *genai.Part into LLMRequest.Contents
// before the next LLM call. This is the only way to deliver multimodal
// content to the model without serializing it through JSON as base64 text,
// which would corrupt the model's view of binary files (PDFs, images...).
type loadArtifactTool struct{}

const loadArtifactName = "load_artifact"

const loadArtifactDescription = "Load a previously saved artifact by name and inject its contents into the conversation as a multimodal attachment. " +
	"Use this when the user attached a file to a previous message and you need to read it, or to retrieve content saved earlier with save_artifact. " +
	"Call list_artifacts first if you need to see what's available."

func (t *loadArtifactTool) Name() string        { return loadArtifactName }
func (t *loadArtifactTool) Description() string { return loadArtifactDescription }
func (t *loadArtifactTool) IsLongRunning() bool { return false }

// Declaration is read by ADK to advertise the tool to the LLM.
func (t *loadArtifactTool) Declaration() *genai.FunctionDeclaration {
	return &genai.FunctionDeclaration{
		Name:        loadArtifactName,
		Description: loadArtifactDescription,
		Parameters: &genai.Schema{
			Type: "OBJECT",
			Properties: map[string]*genai.Schema{
				"name": {
					Type:        "STRING",
					Description: "Filename of the artifact to load. Must match exactly the name listed in MAGEC_ATTACHED_ARTIFACTS or returned by list_artifacts.",
				},
			},
			Required: []string{"name"},
		},
	}
}

// Run records the artifact name into the FunctionResponse so that
// ProcessRequest can recognise the call on the next turn and inject the
// actual content. We deliberately do NOT load the artifact here because
// returning binary data through a JSON FunctionResponse would force a
// base64 round-trip that the LLM cannot meaningfully consume.
func (t *loadArtifactTool) Run(ctx tool.Context, args any) (map[string]any, error) {
	m, ok := args.(map[string]any)
	if !ok {
		return map[string]any{"success": false, "message": fmt.Sprintf("unexpected args type: %T", args)}, nil
	}
	name, _ := m["name"].(string)
	if name == "" {
		return map[string]any{"success": false, "message": "name is required"}, nil
	}
	return map[string]any{
		"success": true,
		"name":    name,
		"message": fmt.Sprintf("Artifact %q is being attached to the conversation. Read it from the next user message.", name),
	}, nil
}

// ProcessRequest is invoked by ADK on every LLM turn. It performs two tasks:
//
//  1. Self-registration: every tool must announce itself in req.Tools (so Run()
//     can be dispatched) and req.Config.Tools (so the LLM knows the tool
//     exists). ADK's built-in functiontool does this via the internal
//     toolutils.PackTool helper, which we replicate here since we cannot import
//     internal packages.
//
//  2. Multimodal injection: when the previous turn's last content is a
//     FunctionResponse for load_artifact, the artifact is loaded via the
//     session artifact service and its original *genai.Part is appended INTO
//     the same Content that holds the FunctionResponse. This is critical for
//     ContextGuard compatibility: ContextGuard tracks a "watermark" of how
//     many req.Contents entries existed at the last compaction, and on the
//     next turn slices req.Contents starting at that index. If we appended
//     the artifact as a brand-new Content, the count would diverge from the
//     real session events (ADK's ContentsRequestProcessor copies one Content
//     per persisted event) and the watermark would skip a real event,
//     leaving an orphan tool_result that Anthropic rejects with
//     "unexpected tool_use_id" 400 errors. Mutating Parts of the existing
//     cloned Content keeps "1 session event = 1 req.Contents entry"
//     invariant intact. The clone happens in ContentsRequestProcessor, so
//     the persisted event is not affected.
func (t *loadArtifactTool) ProcessRequest(ctx tool.Context, req *model.LLMRequest) error {
	if err := packSelf(req, t); err != nil {
		return err
	}

	if len(req.Contents) == 0 {
		return nil
	}
	last := req.Contents[len(req.Contents)-1]
	if last == nil || len(last.Parts) == 0 {
		return nil
	}
	fnResp := last.Parts[0].FunctionResponse
	if fnResp == nil || fnResp.Name != loadArtifactName {
		return nil
	}
	name, _ := fnResp.Response["name"].(string)
	if name == "" {
		return nil
	}

	resp, err := ctx.Artifacts().Load(ctx, name)
	if err != nil {
		return fmt.Errorf("load_artifact: failed to load %q: %w", name, err)
	}
	if resp == nil || resp.Part == nil {
		return fmt.Errorf("load_artifact: artifact %q has no content", name)
	}
	last.Parts = append(last.Parts,
		genai.NewPartFromText(fmt.Sprintf("Contents of artifact %q:", name)),
		resp.Part,
	)
	return nil
}

// packSelf registers the tool in req.Tools and its declaration in
// req.Config.Tools, mirroring ADK's internal toolutils.PackTool. Without this,
// the LLM never sees the tool in its available function list and cannot call
// it. ADK's tool dispatch loop also reads req.Tools to find the handler for a
// FunctionCall, so missing this entry would make any call dead-end too.
func packSelf(req *model.LLMRequest, t *loadArtifactTool) error {
	if req.Tools == nil {
		req.Tools = make(map[string]any)
	}
	name := t.Name()
	if _, ok := req.Tools[name]; ok {
		return nil
	}
	req.Tools[name] = t

	if req.Config == nil {
		req.Config = &genai.GenerateContentConfig{}
	}
	decl := t.Declaration()
	if decl == nil {
		return nil
	}
	for _, existing := range req.Config.Tools {
		if existing != nil && existing.FunctionDeclarations != nil {
			existing.FunctionDeclarations = append(existing.FunctionDeclarations, decl)
			return nil
		}
	}
	req.Config.Tools = append(req.Config.Tools, &genai.Tool{
		FunctionDeclarations: []*genai.FunctionDeclaration{decl},
	})
	return nil
}

// URLArgs are the inputs to get_artifact_url.
type URLArgs struct {
	Name string `json:"name"`
}

// URLResult is what the model receives after a successful URL build.
type URLResult struct {
	Success   bool   `json:"success"`
	URL       string `json:"url,omitempty"`
	ExpiresAt int64  `json:"expires_at,omitempty"`
	MIMEType  string `json:"mime_type,omitempty"`
	Message   string `json:"message"`
}

// getArtifactURL produces a short-lived, signed download URL for an
// artifact. It loads the artifact first to confirm it exists and to capture
// its MIME type, then asks the configured ArtifactURLBuilder to mint the
// URL. App, user and session IDs are sourced from tool.Context so the
// caller never has to pass them in (and cannot pass a foreign session by
// mistake).
//
// Like the rest of the toolset, user-facing failures come back as
// URLResult{Success:false, Message:...}; real Go errors are reserved for
// impossible states.
func (ts *Toolset) getArtifactURL(ctx tool.Context, args URLArgs) (URLResult, error) {
	if args.Name == "" {
		return URLResult{Success: false, Message: "name is required"}, nil
	}
	if ts.urlBuilder == nil {
		return URLResult{Success: false, Message: "ephemeral URLs are not enabled on this server"}, nil
	}

	resp, err := ctx.Artifacts().Load(ctx, args.Name)
	if err != nil {
		return URLResult{Success: false, Message: fmt.Sprintf("artifact %q not found: %v", args.Name, err)}, nil
	}
	if resp == nil || resp.Part == nil {
		return URLResult{Success: false, Message: fmt.Sprintf("artifact %q has no content", args.Name)}, nil
	}

	mime := "application/octet-stream"
	switch {
	case resp.Part.InlineData != nil && resp.Part.InlineData.MIMEType != "":
		mime = resp.Part.InlineData.MIMEType
	case resp.Part.Text != "":
		mime = "text/plain"
	}

	built, err := ts.urlBuilder(ArtifactURLRequest{
		AppName:   ctx.AppName(),
		UserID:    ctx.UserID(),
		SessionID: ctx.SessionID(),
		Name:      args.Name,
		MIMEType:  mime,
	})
	if err != nil {
		return URLResult{Success: false, Message: fmt.Sprintf("failed to build URL: %v", err)}, nil
	}

	return URLResult{
		Success:   true,
		URL:       built.URL,
		ExpiresAt: built.ExpiresAt,
		MIMEType:  mime,
		Message:   fmt.Sprintf("Ephemeral URL for %q ready (expires at unix %d).", args.Name, built.ExpiresAt),
	}, nil
}

var _ tool.Toolset = (*Toolset)(nil)
